/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts */
        get: operations["accounts_api_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Runs */
        get: operations["agent_runs_api_agent_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agents */
        get: operations["agents_api_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept */
        post: operations["accept_api_auth_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite */
        post: operations["invite_api_auth_invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_auth_password_change_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_api_auth_password_forgot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/recovery/codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recovery Codes */
        post: operations["recovery_codes_api_auth_recovery_codes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/recovery/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recovery Login */
        post: operations["recovery_login_api_auth_recovery_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset */
        post: operations["reset_api_auth_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Link */
        post: operations["reset_link_api_auth_reset_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Setup */
        post: operations["setup_api_auth_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth State */
        get: operations["auth_state_api_auth_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar */
        get: operations["calendar_api_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_api_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feeds */
        get: operations["feeds_api_feeds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/halt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Halt */
        post: operations["halt_api_halt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health View */
        get: operations["health_view_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** News */
        get: operations["news_api_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proposals */
        get: operations["proposals_api_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent Proposals
         * @description Proposals decided in the last 10 minutes (newest first), so a decided card says what happened to it.
         */
        get: operations["recent_proposals_api_proposals_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rearm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rearm */
        post: operations["rearm_api_rearm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Research View */
        get: operations["research_view_api_research_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users */
        get: operations["users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable */
        post: operations["disable_api_users_disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable */
        post: operations["enable_api_users_enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/revoke-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Sessions */
        post: operations["revoke_sessions_api_users_revoke_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Role */
        post: operations["set_role_api_users_role_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptRequest */
        AcceptRequest: {
            /**
             * Password
             * @default
             */
            password: string;
            /**
             * Token
             * @default
             */
            token: string;
        };
        /** AcceptResponse */
        AcceptResponse: {
            /** Email */
            email: string;
            /** Totp Uri */
            totp_uri: string;
        };
        /** AccountSummary */
        AccountSummary: {
            /**
             * Account Class
             * @enum {string}
             */
            account_class: "raw" | "standard" | "unknown";
            /** Account Id */
            account_id: string;
            /** Broker */
            broker: string;
            /** Day Pnl Pct */
            day_pnl_pct: number;
            /** Drawdown Pct */
            drawdown_pct: number;
            /** Equity */
            equity: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "demo" | "live" | "paper";
            /** Open Positions */
            open_positions: number;
            /**
             * Stage
             * @enum {string}
             */
            stage: "normal" | "size_down" | "halted";
            /** Week Pnl Pct */
            week_pnl_pct: number;
        };
        /**
         * ActiveBlackout
         * @description An entry blackout an engine is enforcing now (from state/engine_<account>.json).
         */
        ActiveBlackout: {
            /** Accounts */
            accounts: string[];
            /**
             * Kind
             * @enum {string}
             */
            kind: "calendar" | "news_shock";
            /** Received Utc */
            received_utc: string | null;
            /** Title */
            title: string;
            /** Ts Utc */
            ts_utc: string | null;
        };
        /**
         * AgentHealthRow
         * @description One champion's drift and health (state/drift.json, research/drift.py AgentHealth) with its halt state.
         */
        AgentHealthRow: {
            /** Agent Id */
            agent_id: string;
            /** Backtest Dd */
            backtest_dd: number | null;
            /** Brier */
            brier: number | null;
            /** Capital Weight */
            capital_weight: number | null;
            /** Cusum */
            cusum: number;
            /** Cusum Alarm */
            cusum_alarm: boolean;
            /** Dd 30D */
            dd_30d: number;
            /** Ece */
            ece: number | null;
            /** Halt Reasons */
            halt_reasons: string[];
            /** Halted */
            halted: boolean;
            /** Halted Since */
            halted_since: string | null;
            /** N Calib */
            n_calib: number;
            /** N Live Rows */
            n_live_rows: number;
            /** Notes */
            notes: string[];
            /** Psi Size Down */
            psi_size_down: string[];
            /** Psi Warn */
            psi_warn: string[];
            /** Size Factor */
            size_factor: number;
            /** Version */
            version: string;
        };
        /** AgentRow */
        AgentRow: {
            /** Agent Id */
            agent_id: string;
            /** Calibration Ece */
            calibration_ece: number;
            /** Capital Weight */
            capital_weight: number;
            /** Expectancy R */
            expectancy_r: number;
            /** Family */
            family: string;
            /** Fitness */
            fitness: number;
            /** Generation */
            generation: number;
            /** Hit Rate */
            hit_rate: number;
            /** N Trades */
            n_trades: number;
            /** Parent Id */
            parent_id: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "shadow" | "live" | "retired";
        };
        /**
         * AgentRunRow
         * @description One staff-agent run (data steward, risk officer, journal coach, improvement agent) and its report.
         */
        AgentRunRow: {
            /** Cost Usd */
            cost_usd: number;
            /** Detail */
            detail: string | null;
            /** Report */
            report: string | null;
            /** Role */
            role: string;
            /**
             * Started Utc
             * Format: date-time
             */
            started_utc: string;
            /** Status */
            status: string;
            /** Turns */
            turns: number;
        };
        /** AuthState */
        AuthState: {
            /** Needs Setup */
            needs_setup: boolean;
            /** Users */
            users: number;
        };
        /**
         * CalendarEvent
         * @description One archived economic-calendar event. Tier 1 (US CPI, NFP, FOMC, PCE) carries its entry-blackout window.
         */
        CalendarEvent: {
            /** Blackout End */
            blackout_end: string | null;
            /** Blackout Start */
            blackout_start: string | null;
            /** Country */
            country: string;
            /** Event Id */
            event_id: string;
            /** Forecast */
            forecast: string;
            /** Impact */
            impact: string;
            /** Previous */
            previous: string;
            /** Tier */
            tier: number;
            /** Title */
            title: string;
            /**
             * Ts Utc
             * Format: date-time
             */
            ts_utc: string;
        };
        /** CalendarResponse */
        CalendarResponse: {
            active_blackout: components["schemas"]["ActiveBlackout"] | null;
            /** Events */
            events: components["schemas"]["CalendarEvent"][];
            /** Note */
            note: string | null;
            /**
             * Now
             * Format: date-time
             */
            now: string;
        };
        /**
         * ChangePasswordRequest
         * @description Logged in. Revokes the user's other sessions.
         */
        ChangePasswordRequest: {
            /**
             * Current Password
             * @default
             */
            current_password: string;
            /**
             * New Password
             * @default
             */
            new_password: string;
            /**
             * Totp
             * @default
             */
            totp: string;
        };
        /** CusumPoint */
        CusumPoint: {
            /** S */
            s: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Z */
            z: number;
        };
        /** CusumTrace */
        CusumTrace: {
            /** Agent Id */
            agent_id: string;
            /** Alarm */
            alarm: boolean;
            /** H */
            h: number;
            /** K */
            k: number;
            /** Points */
            points: components["schemas"]["CusumPoint"][];
            /** Version */
            version: string;
        };
        /**
         * DecidedProposal
         * @description A proposal decided in the last few minutes, so its card can show what happened to it.
         *
         *     submitted: decision recorded, the engine applies it (and re-checks the RiskGate) on its next tick;
         *     approved: the order was sent; refused: approved, but the RiskGate re-check refused the order (see `refusal`);
         *     rejected: with its reason code; expired: nobody decided within the window.
         */
        DecidedProposal: {
            /** Account Id */
            account_id: string;
            /** Agent Id */
            agent_id: string;
            /** Decided By */
            decided_by?: string | null;
            /** Entry */
            entry: number;
            /** Ev R */
            ev_r: number;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Lots */
            lots: number;
            /** P */
            p: number;
            /** Proposal Id */
            proposal_id: string;
            /** Reason Code */
            reason_code?: ("news" | "cost" | "discretion" | "duplicate" | "other") | null;
            /**
             * Refusal
             * @default []
             */
            refusal: string[];
            /** Risk Usd */
            risk_usd?: number | null;
            /**
             * Side
             * @enum {string}
             */
            side: "long" | "short";
            /** Spread Points */
            spread_points: number;
            /**
             * Status
             * @enum {string}
             */
            status: "submitted" | "approved" | "rejected" | "expired" | "refused";
            /** Stop */
            stop: number;
            /** Target */
            target: number;
            /** Top Features */
            top_features: [
                string,
                number
            ][];
            /** Tradingview Url */
            tradingview_url?: string | null;
        };
        /** Decision */
        Decision: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "reject";
            /** Proposal Id */
            proposal_id: string;
            /** Reason Code */
            reason_code?: ("news" | "cost" | "discretion" | "duplicate" | "other") | null;
        };
        /** DecisionResult */
        DecisionResult: {
            /** Outcome */
            outcome: string;
        };
        /** FeedHealth */
        FeedHealth: {
            /** Account Id */
            account_id: string;
            /** Last Tick Age S */
            last_tick_age_s: number;
            /** Spread Points */
            spread_points: number;
            /** Supervisor Heartbeat Age S */
            supervisor_heartbeat_age_s: number;
            /** Terminal Connected */
            terminal_connected: boolean;
            /** Webhook P99 Latency S */
            webhook_p99_latency_s: number | null;
        };
        /**
         * ForgotPasswordRequest
         * @description Self-service reset with a current authenticator code. The same 403 for an unknown email or a wrong code.
         */
        ForgotPasswordRequest: {
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * New Password
             * @default
             */
            new_password: string;
            /**
             * Totp
             * @default
             */
            totp: string;
        };
        /** GateCheck */
        GateCheck: {
            /** Detail */
            detail: string;
            /** Name */
            name: string;
            /** Passed */
            passed: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HaltRequest */
        HaltRequest: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * Headline
         * @description One collected headline; unscored items (prefiltered out or over the daily cap) have relevance and tags null.
         */
        Headline: {
            /** Dollar */
            dollar: ("positive" | "negative" | "neutral") | null;
            /** Item Id */
            item_id: string;
            /** Link */
            link: string | null;
            /** Rates */
            rates: ("hawkish" | "dovish" | "neutral") | null;
            /**
             * Received Utc
             * Format: date-time
             */
            received_utc: string;
            /** Relevance */
            relevance: number | null;
            /** Risk */
            risk: ("risk_on" | "risk_off" | "neutral") | null;
            /** Shock */
            shock: boolean;
            /** Source */
            source: string;
            /** Surprise */
            surprise: ("beat" | "miss" | "inline" | "none") | null;
            /** Title */
            title: string;
            /**
             * Ts Utc
             * Format: date-time
             */
            ts_utc: string;
        };
        /**
         * HealthCheckRow
         * @description One deterministic health check (goldbot/ops/health.py), evaluated when the view is requested.
         */
        HealthCheckRow: {
            /** Name */
            name: string;
            /** Reason */
            reason: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "warn" | "fail";
        };
        /** HealthView */
        HealthView: {
            /** Agents */
            agents: components["schemas"]["AgentHealthRow"][];
            /** Checks */
            checks: components["schemas"]["HealthCheckRow"][];
            /** Cusum */
            cusum: components["schemas"]["CusumTrace"][];
            /** Dd Mult */
            dd_mult: number;
            /** Drift Error */
            drift_error: string | null;
            /** Drift Ts */
            drift_ts: string | null;
            /** Errors */
            errors: {
                [key: string]: string;
            };
            /**
             * Generated Utc
             * Format: date-time
             */
            generated_utc: string;
            psi: components["schemas"]["PsiHeatmap"];
            /** Reliability */
            reliability: components["schemas"]["ReliabilityCurve"][];
            system_halt: components["schemas"]["SystemHaltView"] | null;
        };
        /**
         * HypothesisDoc
         * @description The hypothesis portfolio (docs/research/hypotheses.md), its tables parsed, read-only.
         */
        HypothesisDoc: {
            /** Note */
            note: string | null;
            /** Path */
            path: string;
            /** Tables */
            tables: components["schemas"]["HypothesisTable"][];
            /** Updated Utc */
            updated_utc: string | null;
        };
        /** HypothesisTable */
        HypothesisTable: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: string[][];
            /** Title */
            title: string;
        };
        /** InviteRequest */
        InviteRequest: {
            /** Email */
            email: string;
            /**
             * Role
             * @default viewer
             * @enum {string}
             */
            role: "approver" | "viewer";
        };
        /** InviteResponse */
        InviteResponse: {
            /** Expires H */
            expires_h: number;
            /** Invite Token */
            invite_token: string;
        };
        /**
         * JobRow
         * @description One scheduler job as the dashboard shows it (from state/scheduler.json).
         */
        JobRow: {
            /** Failures */
            failures: number;
            /** Heartbeat Age S */
            heartbeat_age_s: number;
            /** Last Error */
            last_error: string | null;
            /** Last Finished */
            last_finished: string | null;
            /** Last Ok */
            last_ok: boolean | null;
            /** Last Slot */
            last_slot: string | null;
            /** Name */
            name: string;
            /** Next Slot */
            next_slot: string | null;
            /** Runs */
            runs: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Password
             * @default
             */
            password: string;
            /**
             * Totp
             * @default
             */
            totp: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Email */
            email: string;
            /** Expires In */
            expires_in: number;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "approver" | "viewer";
            /** Token */
            token: string;
        };
        /** Me */
        Me: {
            /** Email */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "approver" | "viewer";
        };
        /** Ok */
        Ok: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** PlanFamily */
        PlanFamily: {
            /** Best Dsr */
            best_dsr: number | null;
            /** Blocked */
            blocked: boolean;
            /** Evidence */
            evidence: number;
            /** Family */
            family: string;
            /** Flags */
            flags: string[];
            /** Median Auc */
            median_auc: number | null;
            /** Shadow Trades */
            shadow_trades: number;
            /** Trials */
            trials: number;
        };
        /** PlanFocus */
        PlanFocus: {
            /** Budget */
            budget: number;
            /** Evidence */
            evidence: number;
            /** Family */
            family: string;
            /** Rank */
            rank: number;
            /** Reasons */
            reasons: string[];
        };
        /** Proposal */
        Proposal: {
            /** Account Id */
            account_id: string;
            /** Agent Id */
            agent_id: string;
            /** Entry */
            entry: number;
            /** Ev R */
            ev_r: number;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Lots */
            lots: number;
            /** P */
            p: number;
            /** Proposal Id */
            proposal_id: string;
            /** Risk Usd */
            risk_usd?: number | null;
            /**
             * Side
             * @enum {string}
             */
            side: "long" | "short";
            /** Spread Points */
            spread_points: number;
            /** Stop */
            stop: number;
            /** Target */
            target: number;
            /** Top Features */
            top_features: [
                string,
                number
            ][];
            /** Tradingview Url */
            tradingview_url?: string | null;
        };
        /**
         * PsiHeatmap
         * @description PSI of the top features (rows) per agent (columns); null where the agent does not use the feature.
         */
        PsiHeatmap: {
            /** Agents */
            agents: string[];
            /** Features */
            features: string[];
            /** Size Down */
            size_down: number;
            /** Values */
            values: (number | null)[][];
            /** Warn */
            warn: number;
        };
        /** RearmRequest */
        RearmRequest: {
            /** Totp */
            totp: string;
        };
        /** RecoveryCodesRequest */
        RecoveryCodesRequest: {
            /**
             * Password
             * @default
             */
            password: string;
            /**
             * Totp
             * @default
             */
            totp: string;
        };
        /** RecoveryCodesResponse */
        RecoveryCodesResponse: {
            /** Recovery Codes */
            recovery_codes: string[];
        };
        /**
         * RecoveryLoginRequest
         * @description Owner only: a one-time recovery code in place of the authenticator code.
         */
        RecoveryLoginRequest: {
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Password
             * @default
             */
            password: string;
            /**
             * Recovery Code
             * @default
             */
            recovery_code: string;
        };
        /** RecoveryLoginResponse */
        RecoveryLoginResponse: {
            /** Email */
            email: string;
            /** Expires In */
            expires_in: number;
            /** Recovery Codes Left */
            recovery_codes_left: number;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "approver" | "viewer";
            /** Token */
            token: string;
            /** Totp Uri */
            totp_uri: string;
        };
        /** ReliabilityBin */
        ReliabilityBin: {
            /** Hi */
            hi: number;
            /** Hit Rate */
            hit_rate: number;
            /** Lo */
            lo: number;
            /** Mean P */
            mean_p: number;
            /** N */
            n: number;
        };
        /**
         * ReliabilityCurve
         * @description Predicted p (10 equal bins) against the realised target-hit rate of closed, taken shadow trades.
         */
        ReliabilityCurve: {
            /** Agent Id */
            agent_id: string;
            /** Bins */
            bins: components["schemas"]["ReliabilityBin"][];
            /** Brier */
            brier: number | null;
            /** Ece */
            ece: number | null;
            /** N */
            n: number;
            /** Version */
            version: string | null;
        };
        /**
         * ResearchPlanView
         * @description The research director's latest plan (state/research_plan.json).
         */
        ResearchPlanView: {
            /** Budget */
            budget: {
                [key: string]: number;
            };
            /**
             * Created Utc
             * Format: date-time
             */
            created_utc: string;
            /** Evidence */
            evidence: components["schemas"]["PlanFamily"][];
            /** Focus */
            focus: components["schemas"]["PlanFocus"][];
            /** Grid Budget */
            grid_budget: {
                [key: string]: number;
            };
            /** Holdout From */
            holdout_from: string;
            /** Holdout To */
            holdout_to: string;
            /** Quarter */
            quarter: string;
            /** Quarter Budget */
            quarter_budget: number;
            /** Quarter Used */
            quarter_used: number;
            /** Stale */
            stale: boolean;
            /** Total Budget */
            total_budget: number;
            /** Unallocated */
            unallocated: number;
        };
        /** ResearchView */
        ResearchView: {
            budget: components["schemas"]["TrialBudget"];
            /**
             * Generated Utc
             * Format: date-time
             */
            generated_utc: string;
            hypotheses: components["schemas"]["HypothesisDoc"];
            plan: components["schemas"]["ResearchPlanView"] | null;
            /** Plan Error */
            plan_error: string | null;
            /** Trials */
            trials: components["schemas"]["TrialRow"][];
            /** Trials Total */
            trials_total: number;
        };
        /** ResetLinkResponse */
        ResetLinkResponse: {
            /** Expires H */
            expires_h: number;
            /** Reset Token */
            reset_token: string;
        };
        /**
         * ResetRequest
         * @description Owner-issued one-time link: sets a new password and enrols a new authenticator.
         */
        ResetRequest: {
            /**
             * New Password
             * @default
             */
            new_password: string;
            /**
             * Token
             * @default
             */
            token: string;
        };
        /** RevokeResponse */
        RevokeResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Sessions */
            sessions: number;
        };
        /** RoleChange */
        RoleChange: {
            /** Email */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "approver" | "viewer";
        };
        /** SetupRequest */
        SetupRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /**
             * Setup Code
             * @default
             */
            setup_code: string;
        };
        /**
         * SetupResponse
         * @description The owner's authenticator and 10 one-time recovery codes. Shown once: only their hashes are stored.
         */
        SetupResponse: {
            /** Recovery Codes */
            recovery_codes: string[];
            /** Totp Uri */
            totp_uri: string;
        };
        /** Status */
        Status: {
            blackout?: components["schemas"]["ActiveBlackout"] | null;
            /**
             * Drift Halt
             * @default false
             */
            drift_halt: boolean;
            /**
             * Drift Reasons
             * @default []
             */
            drift_reasons: string[];
            /** Halt Reason */
            halt_reason?: string | null;
            /** Halted */
            halted: boolean;
            /** Halted By */
            halted_by?: string | null;
            /** Mode */
            mode: string;
            /** Pending */
            pending: number;
            /** Supervisor */
            supervisor: {
                [key: string]: unknown;
            };
            /**
             * Supervisor Halt
             * @default false
             */
            supervisor_halt: boolean;
            /**
             * Supervisor Reasons
             * @default []
             */
            supervisor_reasons: string[];
        };
        /** SystemHaltView */
        SystemHaltView: {
            /** Clear Command */
            clear_command: string;
            /** Reasons */
            reasons: string[];
            /** Review Command */
            review_command: string;
            /** Since */
            since: string | null;
        };
        /** TrialBudget */
        TrialBudget: {
            /** Budget */
            budget: number;
            /** Left */
            left: number;
            /** Quarter */
            quarter: string;
            /** Used */
            used: number;
        };
        /**
         * TrialRow
         * @description One research-registry trial (state/research_registry.jsonl). R figures are the rule's own expectancy over
         *     every candidate: gross on mid prices, net of every cost.
         */
        TrialRow: {
            /** Agent Id */
            agent_id: string;
            /** Family */
            family: string;
            /** Gates */
            gates: components["schemas"]["GateCheck"][];
            /** Gates Passed */
            gates_passed: boolean | null;
            /** Gross R */
            gross_r: number | null;
            /** Gross T */
            gross_t: number | null;
            /** N */
            n: number | null;
            /** Net R */
            net_r: number | null;
            /** Net T */
            net_t: number | null;
            /** Rationale */
            rationale: string;
            /** Status */
            status: string;
            /** Timeframe */
            timeframe: string | null;
            /** Trial */
            trial: number;
            /** Ts */
            ts: string | null;
        };
        /** UserRef */
        UserRef: {
            /** Email */
            email: string;
        };
        /** UserRow */
        UserRow: {
            /** Email */
            email: string;
            /** Enabled */
            enabled: boolean;
            /** Last Login */
            last_login: number | null;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "approver" | "viewer";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    accounts_api_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"][];
                };
            };
        };
    };
    agent_runs_api_agent_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunRow"][];
                };
            };
        };
    };
    agents_api_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRow"][];
                };
            };
        };
    };
    accept_api_auth_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_api_auth_invite_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    change_password_api_auth_password_change_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_auth_password_forgot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recovery_codes_api_auth_recovery_codes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryCodesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recovery_login_api_auth_recovery_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryLoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_api_auth_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_link_api_auth_reset_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRef"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetLinkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setup_api_auth_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_state_api_auth_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
        };
    };
    calendar_api_calendar_get: {
        parameters: {
            query?: {
                days?: number;
                max_tier?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feeds_api_feeds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedHealth"][];
                };
            };
        };
    };
    halt_api_halt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HaltRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_view_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthView"];
                };
            };
        };
    };
    jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRow"][];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    news_api_news_get: {
        parameters: {
            query?: {
                hours?: number;
                min_relevance?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Headline"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proposals_api_proposals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"][];
                };
            };
        };
    };
    recent_proposals_api_proposals_recent_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecidedProposal"][];
                };
            };
        };
    };
    rearm_api_rearm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RearmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_view_api_research_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchView"];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRow"][];
                };
            };
        };
    };
    disable_api_users_disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRef"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_api_users_enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRef"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_sessions_api_users_revoke_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRef"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_role_api_users_role_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
