/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts */
        get: operations["accounts_api_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Runs */
        get: operations["agent_runs_api_agent_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agents */
        get: operations["agents_api_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept */
        post: operations["accept_api_auth_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite */
        post: operations["invite_api_auth_invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Setup */
        post: operations["setup_api_auth_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth State */
        get: operations["auth_state_api_auth_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_api_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feeds */
        get: operations["feeds_api_feeds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proposals */
        get: operations["proposals_api_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users */
        get: operations["users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable */
        post: operations["disable_api_users_disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Role */
        post: operations["set_role_api_users_role_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptRequest */
        AcceptRequest: {
            /**
             * Password
             * @default
             */
            password: string;
            /**
             * Token
             * @default
             */
            token: string;
        };
        /** AcceptResponse */
        AcceptResponse: {
            /** Email */
            email: string;
            /** Totp Uri */
            totp_uri: string;
        };
        /** AccountSummary */
        AccountSummary: {
            /**
             * Account Class
             * @enum {string}
             */
            account_class: "raw" | "standard" | "unknown";
            /** Account Id */
            account_id: string;
            /** Broker */
            broker: string;
            /** Day Pnl Pct */
            day_pnl_pct: number;
            /** Drawdown Pct */
            drawdown_pct: number;
            /** Equity */
            equity: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "demo" | "live" | "paper";
            /** Open Positions */
            open_positions: number;
            /**
             * Stage
             * @enum {string}
             */
            stage: "normal" | "size_down" | "halted";
            /** Week Pnl Pct */
            week_pnl_pct: number;
        };
        /** AgentRow */
        AgentRow: {
            /** Agent Id */
            agent_id: string;
            /** Calibration Ece */
            calibration_ece: number;
            /** Capital Weight */
            capital_weight: number;
            /** Expectancy R */
            expectancy_r: number;
            /** Family */
            family: string;
            /** Fitness */
            fitness: number;
            /** Generation */
            generation: number;
            /** Hit Rate */
            hit_rate: number;
            /** N Trades */
            n_trades: number;
            /** Parent Id */
            parent_id: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "shadow" | "live" | "retired";
        };
        /**
         * AgentRunRow
         * @description One staff-agent run (data steward, risk officer, journal coach, improvement agent) and its report.
         */
        AgentRunRow: {
            /** Cost Usd */
            cost_usd: number;
            /** Detail */
            detail: string | null;
            /** Report */
            report: string | null;
            /** Role */
            role: string;
            /**
             * Started Utc
             * Format: date-time
             */
            started_utc: string;
            /** Status */
            status: string;
            /** Turns */
            turns: number;
        };
        /** AuthState */
        AuthState: {
            /** Needs Setup */
            needs_setup: boolean;
            /** Users */
            users: number;
        };
        /** Decision */
        Decision: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "reject";
            /** Proposal Id */
            proposal_id: string;
            /** Reason Code */
            reason_code?: ("news" | "cost" | "discretion" | "duplicate" | "other") | null;
        };
        /** DecisionResult */
        DecisionResult: {
            /** Outcome */
            outcome: string;
        };
        /** FeedHealth */
        FeedHealth: {
            /** Account Id */
            account_id: string;
            /** Last Tick Age S */
            last_tick_age_s: number;
            /** Spread Points */
            spread_points: number;
            /** Supervisor Heartbeat Age S */
            supervisor_heartbeat_age_s: number;
            /** Terminal Connected */
            terminal_connected: boolean;
            /** Webhook P99 Latency S */
            webhook_p99_latency_s: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InviteRequest */
        InviteRequest: {
            /** Email */
            email: string;
            /**
             * Role
             * @default viewer
             * @enum {string}
             */
            role: "owner" | "approver" | "viewer";
        };
        /** InviteResponse */
        InviteResponse: {
            /** Expires H */
            expires_h: number;
            /** Invite Token */
            invite_token: string;
        };
        /**
         * JobRow
         * @description One scheduler job as the dashboard shows it (from state/scheduler.json).
         */
        JobRow: {
            /** Failures */
            failures: number;
            /** Heartbeat Age S */
            heartbeat_age_s: number;
            /** Last Error */
            last_error: string | null;
            /** Last Finished */
            last_finished: string | null;
            /** Last Ok */
            last_ok: boolean | null;
            /** Last Slot */
            last_slot: string | null;
            /** Name */
            name: string;
            /** Next Slot */
            next_slot: string | null;
            /** Runs */
            runs: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Password
             * @default
             */
            password: string;
            /**
             * Totp
             * @default
             */
            totp: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Email */
            email: string;
            /** Expires In */
            expires_in: number;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "approver" | "viewer";
            /** Token */
            token: string;
        };
        /** Me */
        Me: {
            /** Email */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "approver" | "viewer";
        };
        /** Ok */
        Ok: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** Proposal */
        Proposal: {
            /** Account Id */
            account_id: string;
            /** Agent Id */
            agent_id: string;
            /** Entry */
            entry: number;
            /** Ev R */
            ev_r: number;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Lots */
            lots: number;
            /** P */
            p: number;
            /** Proposal Id */
            proposal_id: string;
            /**
             * Side
             * @enum {string}
             */
            side: "long" | "short";
            /** Spread Points */
            spread_points: number;
            /** Stop */
            stop: number;
            /** Target */
            target: number;
            /** Top Features */
            top_features: [
                string,
                number
            ][];
            /** Tradingview Url */
            tradingview_url?: string | null;
        };
        /** RoleChange */
        RoleChange: {
            /** Email */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "approver" | "viewer";
        };
        /** SetupRequest */
        SetupRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /**
             * Setup Code
             * @default
             */
            setup_code: string;
        };
        /** Status */
        Status: {
            /** Halted */
            halted: boolean;
            /** Mode */
            mode: string;
            /** Pending */
            pending: number;
            /** Supervisor */
            supervisor: {
                [key: string]: unknown;
            };
        };
        /** TotpEnrolment */
        TotpEnrolment: {
            /** Totp Uri */
            totp_uri: string;
        };
        /** UserRef */
        UserRef: {
            /** Email */
            email: string;
        };
        /** UserRow */
        UserRow: {
            /** Email */
            email: string;
            /** Enabled */
            enabled: boolean;
            /** Last Login */
            last_login: number | null;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "approver" | "viewer";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    accounts_api_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"][];
                };
            };
        };
    };
    agent_runs_api_agent_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunRow"][];
                };
            };
        };
    };
    agents_api_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRow"][];
                };
            };
        };
    };
    accept_api_auth_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_api_auth_invite_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    setup_api_auth_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpEnrolment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_state_api_auth_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
        };
    };
    decide_api_decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feeds_api_feeds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedHealth"][];
                };
            };
        };
    };
    jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRow"][];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    proposals_api_proposals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"][];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRow"][];
                };
            };
        };
    };
    disable_api_users_disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRef"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_role_api_users_role_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
